Add feature of realtime WPM in top left corner
Mithil467/mitype pull request #38
Opened 2020-10-01 08:13 UTC by himadriganguly

This fixes enhancement #32

2020-10-01 14:26 UTC, Mithil467 commented
Hey @himadriganguly! Thanks for the PR.

Currently there are 2 issues with this feature.
- The wpm counter is only updating when a key is pressed, can you make it update every 1/10th of a second or something relative. Otherwise it seems very unpolished. But also pay attention you gotta use non-blocking input and no `while(true)` loops that will cause PCU usage 100% (see https://github.com/Mithil467/mitype/issues/12).
- Another small fix is the issue of cursor is moving to the end of the text as opposed to the last character you typed in sample text.

2020-10-08 13:04 UTC, Mithil467 commented
The latest source on master allows refreshing window every 100 milliseconds @himadriganguly :)

So realtime wpm is possible. Merge the latest code from master and you can continue working on this.
I did test it out locally and it does update every 100 ms but the wpm value is incorrect. Please look into this! 👍🏼

2020-10-13 05:34 UTC, Mithil467 commented
Hey @himadriganguly 👋🏼

Do comment if you are stuck somewhere or you may request review when you think it's required. 😄 

Some points to consider.

- The wpm value was refreshing earlier correctly, but the issue was with the wpm value. But now after the latest commit, it doesn't refresh every frame. 
- Current implementation of `speed_in_wpm` function in calculations.py considers text as the entire text sample. This was fine as we were wanting to calculate it only at the end earlier.
- But now that we want it every frame, an accurate implementation would be
```
current_wpm = (
60 * len(self.current_string.split()) / mitype.timer.get_elapsed_minutes_since_first_keypress(self.start_time)
)
```

This does give realtime wpm as expected :)

2020-10-13 05:45 UTC, himadriganguly commented
@Mithil467 Have you checked the latest code that I have pushed? I haven't changed anything other than the WPM functionality that needs to be displayed. Anyways I will create another function for the WPM calculation and update the code.

2020-10-13 05:49 UTC, Mithil467 commented
Yes I did pull the latest changes. It doesn't update every frame but only upon key press. 

>I will create another function for the WPM calculation and update the code.

You may update the existing function, that would be better! 😄

2020-10-13 08:19 UTC, Mithil467 requested changes

2020-10-13 08:19 UTC, Mithil467 commented on mitype/app.py
> +        if key:
Remove this if statement. Let the function be called even if no key is pressed, that way the stat is updated every frame.

2020-10-13 12:20 UTC, Mithil467 commented
@himadriganguly Thank you so much for this feature! This looks like a nice addition to the project. Good work. :)

2020-10-13 12:21 UTC, merged