Add exit with ctrl+c
Mithil467/mitype pull request #57
Opened 2020-10-09 21:44 UTC by diegoramosb

This PR fixes #43 

Tested with python version - 3.7.3

On operating system - Windows 10

2020-10-10 05:13 UTC, Mithil467 commented
Please make sure the code is linted with black

2020-10-10 23:33 UTC, diegoramosb commented
It should be good now. Sorry about that.

2020-10-11 07:24 UTC, Mithil467 requested changes

2020-10-11 07:24 UTC, Mithil467 commented on mitype/keycheck.py
> +    return key == "\x03"
This function has been repeated

2020-10-11 07:25 UTC, Mithil467 commented
This fix works great! Just remove the duplicate function and we are good to merge this :)

2020-10-13 04:48 UTC, Mithil467 approved these changes
Thank you for the fix! @diegoramosb 😄

2020-10-13 04:51 UTC, merged